### ISSUE TITLE
RA - Events - sprava Publications

### ISSUE THREAD

**Issue by rtrembecky** [ZdruzenieSTROM/webstrom-frontend#141]
Event vytvorit vieme, vieme do aj editovat. Nevieme zatial ale handlovat jeho publications. Nemozu byt sucastou POST (create) / PATCH (edit) requestov, potrebujeme osobitne cally z tychto:

<img width="1452" alt="image" src="https://github.com/ZdruzenieSTROM/webstrom-frontend/assets/6044119/af1eb5bd-1e49-4c5f-8fe5-33014bd72d23">

**Comment by vikibrezinova** [comment]
Vedúci vie založiť nový ročník súťaže (zadá termín, nahrá pozvánku, odkaz na registračný formulár). Po skončení súťaže vie vedúci nahrať zadania a výsledky.

**Comment by Matushl** [comment]
#269 duplicate
