### ISSUE TITLE
Mobil

### ISSUE THREAD

**Issue by rtrembecky** [ZdruzenieSTROM/webstrom-frontend#177]
jedna vec su font sizes, pripadne ine paddingy, co by sa mohlo dost poriesit v #127.

ale bude treba na mobile dost iny layout, basically jeden "stlpec" zo styroch, ktore mame. Dorot chysta design tu: https://www.figma.com/file/5Zt6baPy09ZLPMsZprfDwj/STROM-main-_-GRID-3?type=design&node-id=1941-170&mode=design&t=lfwQyFXgUdxp09Bk-0

**Comment by Matushl** [comment]
Zakladna zmena layoutu je hotovo, je potrebne poriesit este jednotlive stranky, to uz rozvrhnem do mensich issues
