### ISSUE TITLE
Redesignovat "chcem riesit" dialog

### ISSUE THREAD

**Issue by Matushl** [ZdruzenieSTROM/webstrom-frontend#201]
![image](https://github.com/ZdruzenieSTROM/webstrom-frontend/assets/5648837/c5d915ea-ae5c-455a-88dc-dcb2e68714d0)

presunut otazku z title do `DialogContent` (a dat ju ako `h3` a nastavit aby sa necapitalizovalo alebo nejake `body` a dat to boldom :man_shrugging: )

**Comment by michalmasrna1** [comment]
Pozor, rocnik a skola su este vymenene a v nadpise je preklep
