### ISSUE TITLE
Po odhlásení sa zatiaľ čo som v editácii profilu tam ostanem, hlásiac mi meno undefined undefined...

### ISSUE THREAD

**Issue by Ericius208** [ZdruzenieSTROM/webstrom-frontend#218]
self explanatorne celkom, malo by ma presmerovať literally hocikam inam xD

**Comment by Matushl** [comment]
Toto je duplikat/bude to vyriesene tymto issue: https://github.com/ZdruzenieSTROM/webstrom-frontend/issues/194
