### ISSUE TITLE
Pomenovať stránku

### ISSUE THREAD

**Issue by kovacspe** [ZdruzenieSTROM/webstrom-frontend#229]
Aby ako názov tabu v prehliadači nesvietilo `React App`

**Comment by rtrembecky** [comment]
`<Head><title>` v `_app.tsx` to urcuje. ale rychly navrh, rozlisoval by som seminare a potencialne riesil aj titles jednotlivych stranok. nieco ako "Matik - Zadania blablabla".
actually osobitnym pridanim `<Head><title>` do napr. `PageLayout` by sa to mohlo vyriesit cele 🤔 este si getnut seminar z `useSeminarInfo` a title poskladat ako nejaky `` `${seminar} - ${pageTitle}` ``
