### ISSUE TITLE
Zjednotit buttons v dialogoch a formularoch

### ISSUE THREAD

**Issue by Matushl** [ZdruzenieSTROM/webstrom-frontend#230]
Prejst celu aplikaciu a pozriet sa v akom poradi sa nachadzaju buttony. Ak sa nachadzaju na formulari ci dialogu 2 buttony (potvrdit, zrusit) tak je vhodne aby sme mali na celej stranke poziciu pozitivneho a negativneho buttonu konzistente (momentalne je pozitivny vpravo).

QUESTIONS: Chceme buttony situovat do praveho dolneho rohu formu/dialogu? Chceme aby pozitivna odpoved bola v pravo?

**Comment by rtrembecky** [comment]
treba poslat screeny Dorot alebo jej ukazat najblizsie nazivo, no

**Comment by rtrembecky** [comment]
viem si predstavit aj v strede dole nejak tie tlacidla, s dostatocnym rozostupom..
