### ISSUE TITLE
Zmena veľkosti zaklikávacích polí podľa rozmeru okna

### ISSUE THREAD

**Issue by Ericius208** [ZdruzenieSTROM/webstrom-frontend#235]
![image](https://github.com/ZdruzenieSTROM/webstrom-frontend/assets/116378748/4d5c6196-f12b-4c1d-bbe9-1996475be5cb)

Fakt? To mam trafic?

**Comment by michalmasrna1** [comment]
Deje sa to iba pri prilis malej sirke, pri aspon 355px na sirku je to vpohode
