### ISSUE TITLE
Opravovanie - Tlacitko "Zmrazit seriu"

### ISSUE THREAD

**Issue by rtrembecky** [ZdruzenieSTROM/webstrom-frontend#238]
na FE v sekcii opravovania potrebujeme tlacitko "Zmrazit seriu" - zavola POST na endpoint competition/series/ID/results/freeze - BE issue https://github.com/ZdruzenieSTROM/webstrom-backend/issues/288

zmrazenie semestra by malo prebehnut automaticky po zmrazeni vsetkych jeho serii. 

next steps, pripadne oddelit do osobitneho issue:
 - based on `complete` v serii
 - based on ci su vsetky ulohy obodovane.

**Comment by michalmasrna1** [comment]
Preventivne disablovat ten Uzavriet button mi nepride worth it, proste skusis a uvidis.
Zakladam z toho osobitne issues na [BE](https://github.com/ZdruzenieSTROM/webstrom-backend/issues/455) aj [FE](https://github.com/ZdruzenieSTROM/webstrom-frontend/issues/498) aby v tom prehlade bolo vidno kolko uloh maju opravene jednotlive ulohy nech tie neopravene nemusi clovek hladat rucne.
