### ISSUE TITLE
Poskytnut uzivatelovi navod ako konvertovat riesenie do PDF a dat ho niekde dostupne a viditelne

### ISSUE THREAD

**Issue by kovacspe** [ZdruzenieSTROM/webstrom-frontend#247]

**Comment by vikibrezinova** [comment]
Iný formát sa nedá odovzdať - nedovolí to prehliadač. Môžeme sa zamyslieť, či chceme niekde pridať odporúčanie, že ak má riešenie v inom formáte, ako ho môže skonvertovať. Otázka je kde by to malo písať.

**Comment by vikibrezinova** [comment]
Duplikát k #345
