### ISSUE TITLE
Ak účastník odovzdáva po termíne upozorníme ho

### ISSUE THREAD

**Issue by kovacspe** [ZdruzenieSTROM/webstrom-frontend#249]

**Comment by vikibrezinova** [comment]
@Ericius208 mne tam pise upozornenie, skus to este raz. 
![Screenshot from 2023-12-08 20-51-58](https://github.com/ZdruzenieSTROM/webstrom-frontend/assets/52294703/31fbba36-9a58-4ff4-a7b4-cdacf6b291f9)

**Comment by Matushl** [comment]
momentalne to nejak funguje, nechavame to do sirokeho testovania zatial takto
