### ISSUE TITLE
Zo zadaní sa dá prekliknúť na pravidlá

### ISSUE THREAD

**Issue by kovacspe** [ZdruzenieSTROM/webstrom-frontend#250]
Mala by existovať statická stránka o korešpondenčnom seminári, ktorá bude v podobnom dizajne ako stránky súťaží, bude tam krátky popis, odkaz na pravidlá, archív... bude to v menu. Nahradí to stránku minulé ročníky. Nad zadaniami bude okrem odkazu na par tipov aj odkaz na pravidla/tuto podstranku

**Comment by vikibrezinova** [comment]
Neviem kde sa to stratilo, ale uz opat nemame odkaz na pravidla nad zadaniami

**Comment by Matushl** [comment]
Bolo to odstranene v PR, kde sa pridavalo par tipov na tu stranku (https://github.com/ZdruzenieSTROM/webstrom-frontend/pull/372)
