### ISSUE TITLE
RA - All lists - Filtrovanie, potencialne Search?

### ISSUE THREAD

**Issue by rtrembecky** [ZdruzenieSTROM/webstrom-frontend#264]
Ked budeme mat viac dat, bude sa v nich treba lepsie vyznat, vediet vyfiltrovat based on competition atd.

**Comment by vgeffer** [comment]
@rtrembecky vedelo by sa potom tie filtre aktivovať cez query? Veľmi by to pomohlo pri #269, keďže nested resources tam nemôžeme použiť (po rozkliknutí publications nejakého Event by ťa to poslalo na PublicationList s filtrom podľa idčka eventu)

**Comment by rtrembecky** [comment]
pozeral si toto? malo by to byt mergable, ale pozriem sa dnes na to. vsetko funguje cez query params: https://github.com/ZdruzenieSTROM/webstrom-frontend/pull/510
