### ISSUE TITLE
Tipy ako riešiť

### ISSUE THREAD

**Issue by vikibrezinova** [ZdruzenieSTROM/webstrom-frontend#344]
Niekde pri zadaniach by mal byť link na Tipy ako riešiť - premyslieť, či to bude statická stránka alebo pdf.

**Comment by Matushl** [comment]
Je potrebné sa rozhodnúť, že ako tam naplníme data. Osobne som za to aby to predpokladalo založíme flatpage, ktorý bude obsahovať tieto informacie a bude ten link proste hardcodnuty do FE (ak velmi chceme tak si mozeme pred tym overit ze ci ten flatpage naozaj existuje)

Alebo si moze @kovacspe  nakodit key values do BE a pridat nejake nove srandy do BE kedze ma malo roboty (ale mozno za zamyslenie to stoji)
