### ISSUE TITLE
Uzavretie série pre účastníkov - banner

### ISSUE THREAD

**Issue by vikibrezinova** [ZdruzenieSTROM/webstrom-frontend#349]
V banneri by po termíne malo písať niečo ako úlohy opravujeme, a keď bude séria celá opravená a uzavretá, tak by v banneri malo písať niečo ako poradie je finálne.

**Comment by vgeffer** [comment]
Waiting for [webstrom-backend/#376](https://github.com/ZdruzenieSTROM/webstrom-backend/issues/376)
