### ISSUE TITLE
Stránka pre korešpondenčnú časť

### ISSUE THREAD

**Issue by vikibrezinova** [ZdruzenieSTROM/webstrom-frontend#366]
Mohla by existovať statická stránka o korešpondenčnom seminári, ktorá bude v podobnom dizajne ako stránky súťaží, bude tam krátky popis, odkaz na pravidlá, archív... bude to v menu. Nahradí to stránku minulé ročníky. 

Malo by to slúžiť ako niečo, kde si človek klikne, keď prvýkrát príde na našu stránku a chce zistiť info o korešpondenčnej časti.

**Comment by kovacspe** [comment]
Zatváram jedná sa o dátovú vec
