### ISSUE TITLE
Nastylovat Strom

### ISSUE THREAD

**Issue by Matushl** [ZdruzenieSTROM/webstrom-frontend#383]
Strom ktory sa nachadza pod menu by mal mat podla slov Dorot mal mat pomer dlzok odvesien konstatny. Momentalne zvysla odvesna zalezi od vysky stranky, vodorovna odvesna je percentualne na zaklade sirky stlpca.

Moznou otazkou je ako sa to bude spravat na velkej obravke ked to ma clovek na pol obrazovky napriklad (to jest uzke a vysoke), alebo na tablete, ktory je nad 900 px siroky, ale teoreticky, ma vytekat vonku zo stranky?

**Comment by rtrembecky** [comment]
nevzala si teda 5-10 minut, aby nieco nacarbala pre rozne obrazovky?

**Comment by Matushl** [comment]
> nevzala si teda 5-10 minut, aby nieco nacarbala pre rozne obrazovky?

no mne to nenapadlo si to od nej pytat  - ked sme boli na chate, tak som si neuvedomil tento problem s vysokymi obrazovkami

**Comment by kovacspe** [comment]
Mali sme pripomienku ... neviem ci relevantnu ale nas strom v logu ma len dva trojuholniky

**Comment by kovacspe** [comment]
Tu je nejake riesenie, ktore nam niekto napisal ... neviem ci funguje
```
.StromLogo_tree__BVqdS {
    height: 100%;
    width: 100%;
    background-color: #000;
    -webkit-clip-path: polygon(100% 0, 100% 100%, 45% 100%, 96% 63%, 55% 63%, 96% 30%, 65% 30%);
    clip-path: polygon(100% 0, 100% 100%, 90% 100%, 90% 80%, 35% 80%, 90% 35%, 56% 35%);
}
```
menil som iba clip-path: polygon"

**Comment by kovacspe** [comment]
Este aj paticka prekryva strom

**Comment by Matushl** [comment]
Pre milestone 2.0 sme sa rozhodli ze nam staci main menu, ktore bude stale zobrazene stale bez moznosi ho schovavat. v 3.0 sa mozeme venovat tomu aby sme vymysleli ako ho urobit aby sme s nim boli spokonny pre rozne velkosti obrazovky.

**Comment by Matushl** [comment]
je mozne sa inspirovat tym ako je urobena stranka crossroad #132
