### ISSUE TITLE
Mobil - Zadania

### ISSUE THREAD

**Issue by Matushl** [ZdruzenieSTROM/webstrom-frontend#388]
![image](https://github.com/ZdruzenieSTROM/webstrom-frontend/assets/5648837/af68dcdd-51ca-46cb-b892-0522e64ca22d)
- tlacitka su prilis daleko od seba
- par tipov vyzera a sprava sa divne

**Comment by kovacspe** [comment]
Ešte aj na mobile sa nedá kliknúť na moje riešenie
