### ISSUE TITLE
Diskusia pri sériach, ktoré su uzavreté

### ISSUE THREAD

**Issue by vikibrezinova** [ZdruzenieSTROM/webstrom-frontend#397]
Je otazka, ci nechceme mat moznost zobrazit si staru diskusiu aj pri uzavretych seriach (mozno si niekto chce pozriet odpoved aj po termine), aktualne sa k nej neda dostat.

**Comment by Matushl** [comment]
ano chceme aby tam bola mozost navstivit diskusiu aj starych serii
