### ISSUE TITLE
Nahratý vzorák sa nedá zobraziť

### ISSUE THREAD

**Issue by vikibrezinova** [ZdruzenieSTROM/webstrom-frontend#400]
Keď vedúci nahrá vzorák cez vedúcovskú sekciu Opravovanie k nejakej úlohe, tak potom si ani ten vedúci ani účastník nevedia zobraziť vzorák (hádže to 404).

**Comment by Matushl** [comment]
bud to treba opravit alebo zabezpecit aby sa nic nenahravalo (disable)

**Comment by vikibrezinova** [comment]
funguje
