### ISSUE TITLE
Tlačidlo GPDR pri registrácií - opraviť

### ISSUE THREAD

**Issue by kovacspe** [ZdruzenieSTROM/webstrom-frontend#413]
Dizajnovo je divné a malo by GDPR otvoriť v novom okne aby ti nepremazalo vyplnene veci

**Comment by vgeffer** [comment]
GDPR sa otvorí na novom okne, no pridávam aj feature, že pred odchodom z formu ti to vyhodí dialog že prídeš o dáta
