### ISSUE TITLE
Nejde uložiť body pri manualnom nahodeni

### ISSUE THREAD

**Issue by kovacspe** [ZdruzenieSTROM/webstrom-frontend#428]
Keď nahravam opravené riešenia, zmaže to všetky body ktoré som predtým zapísala ak som ich nedala samé uložiť. Teda som nahrala riešenie a zmizli všetky body zadané predtým.

**Comment by Matushl** [comment]
@vgeffer daj tu tu tvoji gucci kontrolku na opustenie stranky
