### ISSUE TITLE
Chybová hláška neprebiehajuca sutaz

### ISSUE THREAD

**Issue by kovacspe** [ZdruzenieSTROM/webstrom-frontend#430]
Ak súťaž neprebieha tak chybová hláška sa nespracuje a hodí axios error

**Comment by michalmasrna1** [comment]
Nepodarilo sa mi zreprodukovat, ak ziadna sutaz neprebieha (dokonca aj ked vobec ziadna neexistuje), zobrazi sa:
![image](https://github.com/user-attachments/assets/76df69a4-7081-4736-b0d8-223af70673ea)

Rovnako ist na /akcie/neexistujuca-akcia spravne presmeruje.

Potrebujem bud viac vysvetlenia co presne je zle alebo to ak nemas tak to zavri @kovacspe .

**Comment by kovacspe** [comment]
Tu je celý popis

Pri pokuseni sa o prihlasenie do semestra, teda po pokuse o odovzdanie a potvrdeni korektnosti udajov som dostal axios error popup. Vystup  z konzoly:

Request URL:
https://test.strom.sk/api/competition/event/3/register
Request Method:
POST
Status Code:
400 Bad Request
Remote Address:
158.197.17.134:443
Referrer Policy:
strict-origin-when-cross-origin

Response:
["Súťaž aktuálne neprebieha."]

**Comment by vikibrezinova** [comment]
nevieme to zreprodukovat, ak sutaz neprebieha, tak pri ulohach nezobrazuje tlacitko odovzdat
