### ISSUE TITLE
Prerobit podrobnosti prispevkov

### ISSUE THREAD

**Issue by Matushl** [ZdruzenieSTROM/webstrom-frontend#493]
podrobnosti by sa uz nemali zobrazovat vo fancy okne ale mali by fungovat len ako "zobrazit viac" fukncionalita ktora zobrazi text pod uz viditelnym prispevkom

**Comment by kovacspe** [comment]
Padol nápad generovať to skoro celé automaticky (na backende to už čiastočne má vymyslenú mechaniku), pričom by tam boli dve kategórie čo bolo a čo bude ... treba to ale nadizjanovať. Čo bolo by zaroven zobrazovalo iba posledny polrok, pripadne poslednych niekolko veci
