### ISSUE TITLE
SemesterAdministration pridat statistiky opravenosti uloh

### ISSUE THREAD

**Issue by michalmasrna1** [ZdruzenieSTROM/webstrom-frontend#498]
Aby clovek nemusel hladat ktore ulohy este maju neopravene riesenia, bolo by dobre pridat ze kolko z kolko uloh uz je opravenych (ma body).
Predstavujem si to asi takto:
1. ÚLOHA (0/44)    2. ÚLOHA (42/43)    3. ÚLOHA (50/50) ...

Pripadne miesto 50/50 by tam mohla byt uz iba fajocka alebo cosi.

Caka to na backend issue https://github.com/ZdruzenieSTROM/webstrom-backend/issues/455

**Comment by vikibrezinova** [comment]
este by tam mohlo byt, ze ci uz je nahraty vzorak
